apiVersion: v1
kind: Service
  metadata:
    name: photomanager
    labels:
      app: photomanager
  spec:
    ports:
    - port: 3000
      targetPort: http-server
    selector:
      app: photomanager
    type: LoadBalancer